#静态请求配置
spring:
  freemarker:
    cache: false #页面不加载缓存
  devtools:
    restart:
      enabled: true  #热重启
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:  #数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/esshop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: daming
    #集中解决各种编码问题
    banner:
      charset: UTF-8
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
    messages:
      encoding: UTF-8
  messages:
    basename: msg/home
  servlet:
    multipart: #配置文件上传大小
      max-file-size: 5MB
      max-request-size: 100MB
mybatis:
  #config-location: classpath:mybatis/mabatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: #mybatis全局配置文件
    map-underscore-to-camel-case: true

